# .travis.yml
language: ruby
rvm:
    - 1.9.3
script:
    - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
    - psql -c 'create database "unfuck-test";' -U postgres
    - cp config/database.yml.default config/database.yml