embed_assets: off

template_function: Mustache.template

template_extension: html.mustache

javascripts:
  workspace:
    - app/assets/javascripts/jammit-mustache.js
  templates:
    - app/assets/javascripts/templates/**/*.mustache
