# Facebook app information can be found at
# https://developers.facebook.com/apps

default: &defaults
  appid: "492651730746756"
  secret: "789e7719ff2478bf2ce48c107c7d7da0"

development:
  <<: *defaults

test: &test
  appid: "403193339734308"
  secret: "d5df4dc962c11038fdc1a5c2caf4c1c8"

cucumber:
  <<: *test

production:
  <<: *defaults